Using cpu device
Traceback (most recent call last):
  File "d:\Proyectos\Taller_DRL\frozenlake\frozenlake_ppo\frozenlake_ppo.py", line 109, in <module>
    model.learn(total_timesteps=params["steps"], callback=custom_callback)
  File "C:\Users\germa\AppData\Local\Programs\Python\Python311\Lib\site-packages\stable_baselines3\ppo\ppo.py", line 311, in learn
    return super().learn(
           ^^^^^^^^^^^^^^
  File "C:\Users\germa\AppData\Local\Programs\Python\Python311\Lib\site-packages\stable_baselines3\common\on_policy_algorithm.py", line 324, in learn
    continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, n_rollout_steps=self.n_steps)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\germa\AppData\Local\Programs\Python\Python311\Lib\site-packages\stable_baselines3\common\on_policy_algorithm.py", line 224, in collect_rollouts
    if not callback.on_step():
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\germa\AppData\Local\Programs\Python\Python311\Lib\site-packages\stable_baselines3\common\callbacks.py", line 114, in on_step
    return self._on_step()
           ^^^^^^^^^^^^^^^
  File "d:\Proyectos\Taller_DRL\frozenlake\frozenlake_ppo\frozenlake_ppo.py", line 48, in _on_step
    elapsed_time = time.time() - self.start_time
                                 ^^^^^^^^^^^^^^^
AttributeError: 'CustomWandbCallback' object has no attribute 'start_time'
